### ISSUE TITLE
Indicate Items in Zotero With Citations

### ISSUE THREAD

**Issue by LPILibrary** [diegodlh/zotero-cita#110]
It is difficult to find the items in Zotero that have citations.

Some indicator or even a method to search and pull together all the items with citations would be helpful.

**Comment by diegodlh** [comment]
Great suggestion! Thanks. There is an open issue to have extra columns for QID and citations. I'm gonna mark this as duplicate of that one.

**Comment by diegodlh** [comment]
Duplicate of #23
