### ISSUE TITLE
Not fetching QID

### ISSUE THREAD

**Issue by joekroese** [diegodlh/zotero-cita#127]
**Describe the bug**
Clicking 'Fetch QID(s)' opens a notification that says 'Cita [C]'. This notification stays around with no further information and the QID is never fetched.

**To Reproduce**
- Click 'Add item(s) by identifier'
- Paste 10.1080/2330443X.2016.1277966
- Right click 'cita' then 'Fetch QID(s)'

A notification pops up and does not change.

**Expected behavior**
I expect the notification to say that it is fetching the QID and then the QID to appear in the QID section of citations.

**Screenshots**
<img width="326" alt="Screenshot 2021-09-01 at 15 03 41" src="https://user-images.githubusercontent.com/7649772/131677446-eddae1ae-7b7c-4e5c-815f-08955efe5934.png">

**Environment:**
 - Zotero version: Zotero 5.0.97-beta.39+dea4a47b6
 - Cita version: 0.2.5
 - OS name and version: macOS Big Sur 11.5.2

**Additional context**
The debug output log from running all steps to reproduce: [cita_debug_output_log.txt](https://github.com/diegodlh/zotero-cita/files/7091368/cita_debug_output_log.txt)

A more concise debug output log that assumes the item is already added (i.e. the log of just running 'Fetch QID(s)'): [cita_debug_output_log_fetch_only.txt](https://github.com/diegodlh/zotero-cita/files/7091369/cita_debug_output_log_fetch_only.txt)

**Comment by miguelrochefort** [comment]
Same problem here using Zotero 5.0.97-beta.43+c5d89f6d0.

**Comment by diegodlh** [comment]
Thank you both for reporting this! The bug was a result of some changes made to Zotero's beta channel. I've fixed it in master with 9a0bf00. I will try to release a new version of Cita including this soon.

If you find other bugs in Zotero beta I'd appreciate it if you could report them, so we make sure Cita is working when Zotero 6.0 is released.

**Comment by diegodlh** [comment]
Dear @joekroese and @miguelrochefort, I've just released Cita v0.3.0 including this fix. As other major changes have been included as well, I have marked it as pre-release and it isn't available for automatic update by Zotero yet. I plan to do this probably by the end of next week. In the mean time, I would appreciate it if you could help me giving it a try an making sure nothing broke by downloading it [here](https://github.com/diegodlh/zotero-cita/releases/tag/v0.3.0). Thanks!

**Comment by joekroese** [comment]
Just tried out the pre-release and it's working! Thanks @diegodlh!

**Comment by miguelrochefort** [comment]
It's working for me too. Thanks for the quick fix!
