### ISSUE TITLE
Switching items does not update the citations tab

### ISSUE THREAD

**Issue by cboulanger** [diegodlh/zotero-cita#158]
**Describe the bug**
If you open the citations tab on item A and then switch to item B in the list, the citation tab still shows the citations from item A. 

**To Reproduce**
- Click on an item in the item list
- Click on the citations tab
- Switch to a different item 
If not reproducible, it might be a bug in the https://github.com/Dominic-DallOsto/zotero-cita/tree/Dominic-DallOsto/issue144 branch that I am on.

**Expected behavior**
The citation tab should update with the citations of the newly selected item

*Environment:**
 - Zotero version: 5.0.96.3
 - Cita version: 0.3.3. 
 - OS name and version: MacOS 11.5.2

**Comment by diegodlh** [comment]
Thanks for reporting this. I'm not being able to reproduce on Zotero 5.0.97-beta.63+035aac30f with latest Cita release 0.3.3 running on Linux Mint. It may be a bug in the development branch as you suggest. I couldn't check that yet. Alternatively, try disabling other addons and see if it may be an addon incompatibility issue.

**Comment by cboulanger** [comment]
In fact, disabling some older Add-ons that I no longer use and restarting seem to have fixed it. I'm closing the issue, in case the behavior returns I can reopen.

**Comment by diegodlh** [comment]
If you could identify which specific addon is causing this (including version number) and confirm that it happens with the latest release of Cita (not the development branch), please reopen and change the title to make it more specific. Thanks!
