### ISSUE TITLE
Fetching citation metadata fails on this item (endless loop)

### ISSUE THREAD

**Issue by champagnealexandre** [diegodlh/zotero-cita#160]
**Describe the bug**
Fetching citation metadata on 10.1038/nature03597 makes the plugin run endlessly (Cita message box hangs)

**To Reproduce**
fetch metadata on 10.1038/nature03597

**Expected behavior**
fetching to work

**Screenshots**
<img width="279" alt="image" src="https://user-images.githubusercontent.com/30211986/152807707-bebfd705-79a3-4413-b72a-cc833f6ff153.png">

**Environment:**
 - Zotero version: 5.0.97-beta.65+15ae72d14
 - Cita version: 0.3.3
 - OS name and version: macOS Monterey 12.1 (21C52)

**Additional context**
don’t think that’s relevant, had no other problem on hundreds of items

suggestion: add a counter to this window, would have helped pinpoint which item was hanging while I went through my whole library

**Comment by Dominic-DallOsto** [comment]
I replicated this by:

* importing that item by DOI into Zotero
* fetching QID
* Syncing citations with Wikidata - it says 44 citations are ready to be 
added but hangs forever "fetching metadata"

No error message appeared in the console.

I'll have to debug properly to see what's going on here... but good catch!

**Comment by Dominic-DallOsto** [comment]
Just got around to debugging this properly but now I can't replicate this issue anymore. I get all 44 citations syncing for me, at least on Ubuntu.

Are you still getting this issue too?

**Comment by champagnealexandre** [comment]
Nope, doesn’t hang anymore... 🤷‍♂️

Guess this was a one timer!
