### ISSUE TITLE
Update dependencies (14 vulnerabilities currently)

### ISSUE THREAD

**Issue by dpriskorn** [diegodlh/zotero-cita#167]
> 14 vulnerabilities (7 moderate, 7 high)
output from NPM

**Comment by retorquere** [comment]
https://overreacted.io/npm-audit-broken-by-design/

**Comment by dpriskorn** [comment]
> https://overreacted.io/npm-audit-broken-by-design/

I inspected these and none of them seem to be a problem worth bothering about, just like the article states! Thanks for the link, I'm new to the mess of NPM.
