### ISSUE TITLE
Lift size on Citation extraction module

### ISSUE THREAD

**Issue by HughP** [diegodlh/zotero-cita#179]
Has any investigation been done on the tasks required or the general amount of work needed to implement the Citation extraction module? Any idea on how many work hours are needed?

**Comment by Dominic-DallOsto** [comment]
Hi. Things haven't been planned out super thoroughly, no.

The main work at the moment is assessing different potential services, how well they perform, and how they could be integrated. Once completed, the rest of the process should proceed quite quickly.

I'll close this issue to concentrate further discussion in #61
