### ISSUE TITLE
Add the "citations" tab in the right panel of the PDF viewer of Zotero

### ISSUE THREAD

**Issue by Futur3r** [diegodlh/zotero-cita#208]
It would be great to have the "citations" tab inside the right panel of the "viewer mode" while reading a PDF.
To be able to view the bibliography of an article dynamically (i.e use cita functionalities) and contribute manually to wikidata while looking directly at the bibliography of an article.

Right now, I need to got back and forth between an article and my library to check if there is the reference I'm looking for.
And I'm not contributing manually through cita because that makes it too tedious.

**Comment by Dominic-DallOsto** [comment]
Great idea!

Do you know any other extensions which modify the PDF reader view in a similar way? That'd help for building this off.

**Comment by Futur3r** [comment]
Unfortunately no.
I know of only one that add a lot of functionalities in the note taking part of the right panel in viewer mode.
It's the plugin [Better Notes](https://github.com/windingwind/zotero-better-notes#readme).

**Comment by Futur3r** [comment]
> Do you know any other extensions which modify the PDF reader view in a similar way? That'd help for building this off.

Now I do ! The [PDF Translate](https://github.com/windingwind/zotero-pdf-translate) plugin adds a tab in the PDF reader view.

**Comment by Futur3r** [comment]
I searched a bit and if I'm not wrong (and I very probably am), adding this:

        //Add Citations tab to the item pane of the pdf reader
        var itemPaneTabboxReader = doc.getElementById('notes-pane-deck');
        ZoteroOverlay.citationsPane(doc, itemPaneTabboxReader);

there -> https://github.com/diegodlh/zotero-cita/blob/20dfda1cb5a05015253b3c3afffaea17653fe221/src/zoteroOverlay.jsx#L430

Could make it work ? Or at least that's the idea ?

**Comment by Dominic-DallOsto** [comment]
Thanks! That added a Citations tab to the PDF reader, but for some 
reason the tab is empty for me.

Once I find out why and fix it, hopefully that's all there is to it...

**Comment by Futur3r** [comment]
In the [zotero-pdf-translate](https://github.com/windingwind/zotero-pdf-translate) add-on, the equivalent of my last code is defined [here](https://github.com/windingwind/zotero-pdf-translate/blob/307b6e4169a925d4152a0dc0bb88fdeba238222e/src/reader.ts#L33).

  getReaderTabContainer(): Element {
    const deck =
      document.querySelector(".notes-pane-deck").previousElementSibling;
    // @ts-ignore
    return deck.selectedPanel;
  }

And that function is used on the line [266](https://github.com/windingwind/zotero-pdf-translate/blob/307b6e4169a925d4152a0dc0bb88fdeba238222e/src/view.ts#L226) of the view.ts.

    tabContainer = this._Addon.reader.getReaderTabContainer();
    const tabbox = tabContainer.querySelector("tabbox") as HTMLElement;
    tabbox.querySelector("tabs").appendChild(tab);

And when I switch from on "library view" to the pdf reader view, I can see that message in the logs 
`zotero(3)(+0000801): Notifier.trigger('select', 'tab', [tab-OkaYFBqR], {"tab-OkaYFBqR":{"type":"reader"}}) called [observers: 4]`

In comparison, when I switch back to the "library view", I see this 
`zotero(3)(+0002388): Notifier.trigger('select', 'tab', [zotero-pane], {"zotero-pane":{"type":"library"}}) called [observers: 4]`

The function **Zotero.Notifier.trigger()** is called [here](https://github.com/zotero/zotero/blob/7e61be9799b16b0492c9bed4ac203ed5e49d5389/chrome/content/zotero/tabs.js#L377).
`Zotero.Notifier.trigger('select', 'tab', [tab.id], { [tab.id]: { type: tab.type } }, true);`

My hypothesis is that you need to pass the corresponding tab id (i.e `[tab-OkaYFBqR]`) and tab type (i.e `{"zotero-pane":{"type":"library"}`) to some function that will know which data of which item to show up ?

**Comment by Dominic-DallOsto** [comment]
Thanks, yeah. I needed to use the Notifier to listen for new tabs being selected to ensure they always have the Citations tab added. And then needed to change a couple of things with the Citations tabs code, because it assumed only one copy of it would ever exist.

It should be working now - I added a PR with these changes and I'll post a test build for you

**Comment by Futur3r** [comment]
Tested it, no problem :) !
