### ISSUE TITLE
Can't use the "Export to File" option in a group library

### ISSUE THREAD

**Issue by Futur3r** [diegodlh/zotero-cita#216]
**Describe the bug**
On an item localized in a **Group library**, I can't use the "Export to File" option in the citation tab.
The "Export..." window do not shows up and there is no error message.

**To Reproduce**

1. Have an item in a Group library.
2. Go in it's citation tab.
3. Add new citations that are not in wikidata.
4. Click on "More".
5. Click on the option "Export to File".

**Expected behavior**
The use as to be prompted with a window called "Export ...", to be able to choose in which format to export the items.

**Screenshots**

**Environment:**
 - Zotero version: 6.0.15
 - Cita version: 0.4.0
 - OS name and version: Linux Mint 21 x86_64, kernel: 5.15.0-53-generic
 
**Logs:**
When clicking on "Export to File"
```
(3)(+0008534): {Cita} Wed Nov 23 2022 13:05:56 GMT+0100 (CET): Getting citations from source item took 11.07723299972713

(4)(+0000003): Tags haven't changed

(4)(+0000000): Relations have not changed for item null/null

(3)(+0000001): Collections have not changed for item null
```

**Comment by Dominic-DallOsto** [comment]
Thanks for the detailed report! I found the issue and fixed it in #217.

I'll do some more testing then make a beta release with the fix soon.

 From what I found the export is failing at the moment for any library 
other than the default.

**Comment by Futur3r** [comment]
Thanks for the time and energy you put in this project !
This extension is becoming vital in my workflow as a student who need to do some scientific research ! :D
I might start to invest some time in cita too, I tried to contribute bibliographic data with OpenRefine or just spreadsheets and Quickstatements ... but I have to say, although using cita can be tedious (for now), it's still is easier and there is less errors in the data. The functionality of Zotero makes human input/checking more accessible.

**Comment by Dominic-DallOsto** [comment]
Thanks a lot for the error reports and suggestions.

I've merged this change into the latest beta release - 0.5.3.

**Comment by Futur3r** [comment]
I just tested it, it works fine, no problem. A big thanks !
