### ISSUE TITLE
DOI, QID and other unique identifiers do not update in Cita pane when changed in Zotero's info pane

### ISSUE THREAD

**Issue by diegodlh** [diegodlh/zotero-cita#292]
**Describe the bug**
If DOI, QID or other unique identifiers are changed in Zotero's Info pane for an item, their values are not correspondingly updated in the Cita pane below. The item has to be unselected and selected again for the change to show in the Cita pane.

**To Reproduce**
1. Change the DOI of an item in Zotero.

**Expected behavior**
The new DOI should show in the corresponding DOI field in the Cita pane.

**Environment:**
 - Zotero version: Zotero 7
 - Cita version: zotero7 development branch
 - OS name and version: Linux

**Additional context**
This did not affect previous versions of Zotero because the Info and Cita pane would not show at the same time (they were separate tabs before).

Note that it does work the other way round. That is, if unique identifier is changed in the Cita pane, it gets immediately updated in the Info pane.

**Comment by Dominic-DallOsto** [comment]
Hmm, yeah. More specifically, I get the following:

1. Select an item
2. Add a DOI in the Info pane, it shows up immediately in the Cita pane
3. Delete it in the Info pane, it also disappears immediately from the Cita pane
4. Add a DOI in the Cita pane, it shows up immediately in the Info pane
5. Delete the DOI in the Cita pane, it disappears immediately from the Info pane
6. Now add a DOI in the Info pane, it **doesn't show up** in the Cita pane

I don't see any errors in the console though
