### ISSUE TITLE
QID is not saved if fetched immediately after erasing previous value

### ISSUE THREAD

**Issue by diegodlh** [diegodlh/zotero-cita#293]
**Describe the bug**
If the QID of an item is fetched immediately after removing its previous QID value, then the new fetched QID is not correctly saved.

**To Reproduce**
1. Select an item with a QID value.
2. Erase the QID value in the Cita pane. Note that it is erased from the item's extra field in the Info pane too.
3. Without changing the item selection, click to fetch the QID for the item from Wikidata.
4. Select another item and then select the previous item again.

**Expected behavior**
In 3. above, the fetched QID should be written to the QID field in the Cita pane. Instead, the field remains empty. Note that the fetched QID is written to the item's extra field in the Info pane.

In 4. above, after deselecting and selecting the item again, the QID fetched before should remain saved. Instead, it is lost. Both from the QID field in the Cita pane and from the extra field in the Info pane.

**Environment:**
 - Zotero version: Zotero 7
 - Cita version: zotero7 development branch
 - OS name and version: Linux

**Additional context**
I wonder whether this may be related in any way to #292, which also involves updating QID and other unique identifier fields in the Cita pane.

**Comment by Dominic-DallOsto** [comment]
I get the same as you after 3. the QID shows up in the info pane but not the Cita pane.

But after 4. the QID shows up in both the Info pane and Cita pane for me.
