### ISSUE TITLE
Double entry in context menu

### ISSUE THREAD

**Issue by cboulanger** [diegodlh/zotero-cita#302]
**Describe the bug**
The CITA entry in the contex menu appears twice

**To Reproduce**
Install plugin

**Expected behavior**
Just one entry

**Screenshots**
![grafik](https://github.com/user-attachments/assets/86d2a43c-14e2-413a-b178-0c0c6d234d8f)

**Environment:**
 - Zotero version: 7.0.5 (64-bit)
 - Cita version: 1.0.0-beta.7
 - OS name and version: Windows 10

**Comment by thebluepotato** [comment]
For additional context, the beta versions seem to incorrectly unload/reload and keep adding to the context menu. A simple restart of Zotero fixes it, but this is of course not ideal.
