### ISSUE TITLE
Zotkat isn't used

### ISSUE THREAD

**Issue by Dominic-DallOsto** [diegodlh/zotero-cita#307]
We currently use the zotkat submodule (https://github.com/UB-Mannheim/zotkat/) for the Wikidata Quickstatements translator, but Zotero actually has a newer, built-in version of the translator (see https://github.com/zotero/translators/blob/master/Wikidata%20QuickStatements.js)

Can we remove zotkat then?

**Comment by thebluepotato** [comment]
My thoughts exactly while adding other translators
