### ISSUE TITLE
Icons in "Citations" tab are too large - macOS

### ISSUE THREAD

**Issue by jdnicholas** [diegodlh/zotero-cita#71]
Using Zotero 5.0.96.2 on macOS Catalina 10.15.7, the "type" and "delete" icons for the citations added are too large and overlap each other - see screenshot below:

<img width="234" alt="Screenshot 2021-04-18 at 16 25 53" src="https://user-images.githubusercontent.com/29875178/115149088-c35fb280-a062-11eb-96a1-45af5b548931.png">

**Comment by diegodlh** [comment]
Thanks, @jdnicholas. I think I know what may be wrong. I'm gonna label this as a bug and try and have it fixed before the [workshops](https://www.wikidata.org/wiki/Wikidata:Zotero/Cita#Presentation_workshop) I'm planning for the end of May.

**Comment by diegodlh** [comment]
This has been fixed in master and should be included in v0.2.1 to be released in these days. Let me know if the problem persists! Thanks for your issue report
