### ISSUE TITLE
Support citation intentions

### ISSUE THREAD

**Issue by diegodlh** [diegodlh/zotero-cita#88]
Support describing citation intentions in CiTO [terms](https://sparontologies.github.io/cito/current/cito.html#objectproperties).

This is being [explored](https://www.biomedcentral.com/collections/cito), for example, with the Journal of Cheminformatics, as stated by Egon Willighagen in his comment [here](https://meta.wikimedia.org/wiki/Wikicite/grant/WikiCite_addon_for_Zotero_with_citation_graph_support#Endorsements). See for example [Q105625784](https://www.wikidata.org/wiki/Q105625784).

Scholia already [supports](https://scholia.toolforge.org/cito/) this, using [P3712](https://www.wikidata.org/wiki/Property:P3712) ( objective of project or action) as qualifier of P2860 (cites work).

This may be related to syncing "cites work" reference fields #29, as both involve property object fields other than the value.

**Comment by Futur3r** [comment]
related to #163

**Comment by diegodlh** [comment]
Indeed, duplicate of #163.
