### ISSUE TITLE
Support citing other item types

### ISSUE THREAD

**Issue by diegodlh** [diegodlh/zotero-cita#9]
Right now, only journal articles are supported as citation target items. Add support for, at least, books and book chapters. Use ISBN instead of DOI in these cases.

**Comment by diegodlh** [comment]
I would like to analyze Wikidata's database dump to find out which are the most popular:
- "instance of" (P31) objects
- "Wikidata property for an identifier" (Q19847637) properties, e.g. DOI (P356)

for both citing and cited items of a citation; i.e., subject and object entities of "cites work" (P2860).
This will help me decide which item types and unique identifiers I should focus on

**Comment by diegodlh** [comment]
Maybe consider PMID/PMCID for journal articles as well

**Comment by diegodlh** [comment]
Support Wikipedia articles. All of them have a QID in Wikidata. Maybe a bot can be developed that adds "cites work" statements to articles' entries in Wikidata, by parsing Cite Q citations in the references.

**Comment by DominicD-823543** [comment]
Would it be possible to add arxiv id (P818) as an identifier? As I can import items by arxiv id into Zotero, it would be great to have that link with retrieving citations.

Does wikidata catalogue arxiv articles currently? Would there by any issues when an arxiv preprint is later published, to then assign it a DOI?

**Comment by diegodlh** [comment]
@Dominic-DallOsto, I'm moving your suggestion to issue #51, as I think it is more relevant there.
