### ISSUE TITLE
Cita does not add items when in a group library

### ISSUE THREAD

**Issue by scannopolis** [diegodlh/zotero-cita#92]
If an element is on a group library, even when stored locally, Cita retrieves the elements from Wikidata but then does not show them. See example here. This file is in a group library and also stored locally -- but then the local element never gets the cites.

![image](https://user-images.githubusercontent.com/9610679/119231889-5cb63480-baf9-11eb-82d1-39dfc15e11d0.png)

**Comment by diegodlh** [comment]
I can confirm this. It has been fixed in the master branch and should be available in the next Cita release. Thanks for reporting!
